# Generated by Django 5.0 on 2023-12-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_alter_sensor_measurement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='Measurement',
            field=models.ManyToManyField(related_name='sensors', through='measurement.SensorOfMeasurement', to='measurement.measurement'),
        ),
    ]
