# Generated by Django 5.0 on 2023-12-17 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_measurement_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
        migrations.CreateModel(
            name='SensorOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.measurement')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='Measurement',
            field=models.ManyToManyField(related_name='measurements', through='measurement.SensorOfMeasurement', to='measurement.measurement'),
        ),
    ]
