# Generated by Django 5.0 on 2023-12-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_remove_measurement_sensor_sensorofmeasurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='Measurement',
            field=models.ManyToManyField(through='measurement.SensorOfMeasurement', to='measurement.measurement'),
        ),
        migrations.AlterField(
            model_name='sensorofmeasurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.sensor'),
        ),
    ]
