# Generated by Django 5.0 on 2023-12-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_measurement_sensor_alter_sensor_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='Measurement',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor'),
        ),
        migrations.DeleteModel(
            name='SensorOfMeasurement',
        ),
    ]
