# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/listsensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "Sony32UK52",
  "description": "Датчик в Гостиной"
}

###

# обновление датчика
PATCH {{baseUrl}}/updatesensor/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor":1,
  "image":"1.jpeg",
  "temperature": 24
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
